user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
  worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        gzip on;
        gzip_types text/plain text/css text/javascript application/javascript application/json text/xml application/xml application/xml+rss;
        listen        80;
        server_name   localhost;
        root          /usr/share/nginx/html;
        index         index.html;

        client_header_buffer_size   1k;
        client_header_timeout       60s;
	    client_body_buffer_size     512m;
        client_max_body_size        110m;

        # Proxy settings
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://gymfish_api:9999/;
        }

        location ~* \.(js|css|svg)$ {
            expires 60d;
            add_header Cache-Control "public";
            try_files $uri =404;
        }
    }
}
